name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential libssl-dev libnss3 libmpv-dev libgtk-3-dev libappindicator3-dev

      - name: Lint fmt
        run: cargo fmt --all -- --check
      - name: Lint clippy
        run: cargo clippy --all --no-deps -- -D warnings
      - name: Build
        run: cargo build